feat: add import for config files from oldmarr
homarr-labs/homarr pull request #1019
Opened 2024-08-23 20:09 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/app/[locale]/manage/boards/_components/create-board-button.tsx
> +              Import from old homarr
Translate

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/app/[locale]/manage/boards/_components/create-board-button.tsx
> +              </Badge>
Beta badge component

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +                params: { expected: "JSON" },
This does not work
![image](https://github.com/user-attachments/assets/db081c8b-c280-44b1-8bc6-a6f569e6e9c1)

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +                params: { maxSize: "1 MB" },
This does not work

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +      file: z
Maybe this validator can be put into validation?

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +        actions.closeModal();
Revalidate path, add notifications

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +          label="Select JSON file"
Translate

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +  const [fileValid, setFileValid] = useState(false);
This one should be changed to true

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +            (!fileValid ? "Invalid configuration file" : undefined)
Show this error only when field is dirty

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +        <Fieldset legend="Apps">
Translate all labels and such

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +  defaultTitle: "Import board",
Translate

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +        <pre>{JSON.stringify(form.values, null, 4)}</pre>
Remove

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +              label: "Remove items",
Test if this works

2024-09-01 19:58 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +        <Button type="submit">Import</Button>
Add cancel button and put in group

2024-09-01 19:58 UTC, Meierschlumpf commented on packages/old-import/src/widgets/definitions/common.ts
> +export type OldmarrWidgetKinds = (typeof oldmarrWidgetKinds)[number];
This already exists in the `old-schema` package

2024-09-01 19:58 UTC, Meierschlumpf commented on packages/validation/src/board.ts
> +    .refine((file) => file.size > 0, { message: "File is empty" }),
Maybe superRefine like with client side file validation

2024-09-02 20:18 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +              label: "Remove items",
Okay sidebars do not quite work yet, I'll need to test it further and fix the issues

2024-09-04 19:42 UTC, Meierschlumpf commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +              label: "Remove items",
Okay just tested it again and it actually works as the sidebars were only moved in the md sized gridstack. So I imported md and everything worked as expected

2024-09-06 19:32 UTC, manuel-rw requested changes

2024-09-06 19:32 UTC, manuel-rw commented on apps/nextjs/package.json
Add asterik to required fields

2024-09-06 19:32 UTC, manuel-rw commented on apps/nextjs/package.json
Improve title of modal

2024-09-06 19:32 UTC, manuel-rw commented on apps/nextjs/package.json
Make ``isDefined`` optional in zod model

2024-09-06 19:32 UTC, manuel-rw commented on apps/nextjs/src/components/manage/boards/import-board-modal.tsx
> +        // This is a workarround until async validation is supported by mantine
Create an issue to track this? Otherwise, this will be forgotten

2024-09-06 19:32 UTC, manuel-rw commented on packages/old-import/src/widgets/definitions/index.ts
> +
Create issue

2024-09-06 21:41 UTC, SeDemal approved these changes
![image](https://github.com/user-attachments/assets/12dfb6b5-5e00-45c3-9f35-9cea7a3c7faf)
Beautiful

I still want to do a real situation testings but otherwise lgtm

2024-09-06 21:41 UTC, SeDemal commented on packages/old-import/src/widgets/definitions/dlspeed.ts
Since the download widget already centralizes all download clients and then displays their speed at the bottom, it means the functionality is already present there too rendering this widget obsolete.
It doesn't display a graph for traffic, but I think eliminating all together is a good idea since most users mistook it for a traffic indicator. If they want to track their internet they are better off using the new dashdot integration instead.

2024-09-07 11:11 UTC, manuel-rw submitted a review, later dismissed

2024-09-07 16:12 UTC, SeDemal approved these changes

2024-09-07 16:13 UTC, merged