feat: add improved search
homarr-labs/homarr pull request #1051
Opened 2024-08-30 22:41 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

### Some screenshots

![image](https://github.com/user-attachments/assets/6bd753df-bfb3-4c17-b170-61ad6390cb43)
![image](https://github.com/user-attachments/assets/8e8ee53b-a198-4d8a-bd7c-611769832248)
![image](https://github.com/user-attachments/assets/1212470a-5773-4fb3-b344-43a1b334e251)
![image](https://github.com/user-attachments/assets/5bd9eafa-d393-416d-a117-63f5e46b866b)
![image](https://github.com/user-attachments/assets/a7e32f7b-c2dd-4809-abbe-5cd66e81ff3d)
![image](https://github.com/user-attachments/assets/c3be16e7-20d9-4eef-8900-be6446237de6)

### Additional thoughts / ideas

My plan is to have the default search engine on the first page (first image) by default and for example on the boards page also have the apps from the board listed below. The whole system is really easy to adapt / add new search modes. It's still a PoC and I'll need to improve the code and add comments so that everyone is able to adjust it.

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/api/src/router/board.ts
> +      // TODO: restrict for access
TODO

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/actions/group-actions.tsx
> +      return <Spotlight.Empty>{t("common.search.nothingFound")}</Spotlight.Empty>;
Add shared component

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/actions/group-actions.tsx
> +    return <></>;
Add loading and error components

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/actions/items/children-action-item.tsx
> +  }
Probably remove as there is hide & filter

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/spotlight.tsx
> +  const [mode, setMode] = useState("default");
Maybe change to `help` for now and change later once we have search engines and something to show on the start page

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/spotlight.tsx
> +          // TODO: Add api to directly interact / maybe even add an option to add a onKeyPress event to modes / groups?
TODO

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/spotlight.tsx
> +              Type <Kbd size="xs">?</Kbd> for help and tips
Add translation

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/components/spotlight.tsx
> +              setChildrenOptions(null);
Also set selectAction to 0

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/lib/group.ts
> +  title: string;
Make translatable

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/lib/mode.ts
> +  help: string | undefined;
Make translatable

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/lib/mode.ts
> +  name: string;
Make translatable

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/modes/app-integration-board/apps-search-group.tsx
> +          <Text>Open app url</Text>
Translate all action components

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/modes/app-integration-board/apps-search-group.tsx
> +      <Text>Select an action for the app</Text>
Translate all detail components

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/modes/app-integration-board/apps-search-group.tsx
> +      />{" "}
Probably not wanted `{" "}`

2024-09-18 13:21 UTC, Meierschlumpf commented on packages/spotlight/src/modes/app-integration-board/index.tsx
> +      TODO: Add tip
Add tips where not yet added

2024-09-18 14:37 UTC, Meierschlumpf commented on packages/spotlight/src/lib/mode.ts
> +  name: string;
Unnecessary as it's only a key, renamed to `key`

2024-09-18 18:56 UTC, manuel-rw requested changes
This is so cool! Thank you. Please also have a look at DeepSource

2024-09-18 18:56 UTC, manuel-rw commented on packages/spotlight/src/components/actions/items/group-action-item.tsx
> +          : undefined;
Can you simplify? This is hard to read

2024-09-18 18:56 UTC, manuel-rw commented on packages/spotlight/src/components/spotlight.tsx
> +        }
Invert to reduce nesting?

2024-09-18 19:27 UTC, Meierschlumpf commented
> This is so cool! Thank you. Please also have a look at DeepSource

Thank you, I also really like it, in a next step I'll add a way to customize the search engines and add a default one. Then I'll add a start page where you can search with that engine or whatever is configured for the specific page (Probably will add a useRegisterSpotlightAction hook or something. So for example the apps of a board are shown directly on the start page

2024-09-19 16:24 UTC, manuel-rw approved these changes

2024-09-20 14:51 UTC, merged