fix: add subscription to health monitoring widget
homarr-labs/homarr pull request #1210
Opened 2024-09-30 20:36 UTC by hillaliy

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-09-30 21:04 UTC, SeDemal commented
Subscriptions should be timestamped, any way you could show that information to the user? 
Like "Last Status Update: 1 second ago".

2024-09-30 21:08 UTC, hillaliy commented
I'll try to add it

2024-10-01 15:21 UTC, hillaliy commented
<img width="337" alt="Screenshot 2024-10-01 at 18 20 49" src="https://github.com/user-attachments/assets/93ca9dae-3aba-474b-ad2a-ad053e8ca113">

2024-10-01 15:44 UTC, SeDemal reviewed
Few other comments for the original widget:
- You should put the widget in a ScrollArea, some browsers have ugly scrollers and since there's a variable amount of disks, it may overflow.

- I noticed you haven't used the RTL translation system at all, at the very least, make all translations with ":" a translation with variable, but preferably use RTL.

2024-10-02 10:40 UTC, hillaliy commented
> Few other comments for the original widget:
> 
> * You should put the widget in a ScrollArea, some browsers have ugly scrollers and since there's a variable amount of disks, it may overflow.
> * I noticed you haven't used the RTL translation system at all, at the very least, make all translations with ":" a translation with variable, but preferably use RTL.

It's already scrolling but I'll add ScrollArea. about RTL can you give me an example how to use?

2024-10-04 12:50 UTC, SeDemal requested changes
There might be other challenges I see with rtl that we need to check up on, but we might just change it as a whole in the project rather than in this PR, so for now let's just make it consistent so we know what to look for when and if we change it

2024-10-04 12:50 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +                              remainder: `${memoryUsage.memFree.GB}GiB (${memoryUsage.memFree.percent}%)`,
`Available: 16GiB (50%)` becomes `16GiB (50%) :Available`, but from what I read it should end up being `(%50) 16GiB :Available`

2024-10-04 12:50 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +                            >{`${healthInfo.cpuUtilization.toFixed(2)}%`}</Text>
Possible rtl needed for '%'

2024-10-04 12:50 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +                            tooltip: `${memoryUsage.memUsed.percent}%`,
rtl percent again

2024-10-04 12:50 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +                              : `${(Number(disk.available) / 1024 ** 3).toFixed(2)} GiB`
I think it would be best to use "humanFileSize" here and in other instances that have a "GiB" or "MiB" or anything of the likes.

2024-10-04 14:10 UTC, hillaliy commented on packages/widgets/src/health-monitoring/component.tsx
> +          const { ref, width } = useElementSize();
The ring size expect a number and cqmin is string. I already try to convert to number but the results don't look good, everything is out of proportion.

2024-10-04 14:12 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +          const { ref, width } = useElementSize();
I'll take a look at it when I have time, it's possible you need to use styling instead

2024-10-15 15:03 UTC, Meierschlumpf requested changes

2024-10-15 15:03 UTC, Meierschlumpf commented on packages/widgets/src/health-monitoring/component.tsx
> +          const { ref, width } = useElementSize();
As you can see in https://github.com/homarr-labs/homarr/pull/1280 there is an issue with the current implementation as we are using a hook within the map and so the amount of hooks will change when new integrations are added

2024-10-15 18:07 UTC, hillaliy commented on packages/widgets/src/health-monitoring/component.tsx
> +          const { ref, width } = useElementSize();
would it be ok If I move the hook outside the map?

2024-10-17 20:40 UTC, Meierschlumpf requested changes

2024-10-17 20:40 UTC, Meierschlumpf commented on packages/widgets/src/health-monitoring/component.tsx
> +  dayjs.extend(duration);
Can be moved underneath imports

2024-10-17 20:40 UTC, Meierschlumpf commented on packages/widgets/src/health-monitoring/component.tsx
> +  const formattedUptime = `${days} ${t("common.information.days")}, ${hours} ${t("common.information.hours")}, ${minutes} ${t("common.information.minutes")}`;
Either revert this as it's a lot more infos or improve it so that it can also work in other languages

2024-10-18 10:45 UTC, Meierschlumpf submitted a review, later dismissed

2024-10-18 12:01 UTC, SeDemal commented on packages/widgets/src/health-monitoring/component.tsx
> +                      className="health-monitoring-disk-card"
Now in line 216, you removed it the change along with the other resolutions along the translation snafu.

2024-10-18 18:08 UTC, SeDemal approved these changes

2024-10-18 18:15 UTC, Meierschlumpf approved these changes

2024-10-18 18:42 UTC, merged