RTL option to RSS widget
homarr-labs/homarr pull request #1247
Opened 2024-10-05 13:06 UTC by hillaliy

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-10-05 14:06 UTC, Meierschlumpf commented
I think this should work already when merging #1246

2024-10-19 04:49 UTC, hillaliy commented
Before:
<img width="367" alt="Screenshot 2024-10-19 at 7 48 12" src="https://github.com/user-attachments/assets/72ec015b-c88f-4546-978f-542ea8d36ead">

After:
<img width="367" alt="Screenshot 2024-10-19 at 7 49 31" src="https://github.com/user-attachments/assets/be0915aa-5e4d-4fb5-8c41-cdeccfe5ade7">

2024-10-20 08:44 UTC, Meierschlumpf requested changes

2024-10-20 08:44 UTC, Meierschlumpf commented on packages/old-import/src/widgets/definitions/rss.ts
> +    anableRtl: boolean;
Typo, would be `enableRtl`

Okay I first thought why we would need an option for that as we already could use `useDirection`, but it makes sense as the source of the RSS feed has obviously not to be in the same language as the user choose.

2024-10-21 10:03 UTC, Meierschlumpf approved these changes

2024-10-21 10:19 UTC, merged