feat: #1243 add api routes
homarr-labs/homarr pull request #1286
Opened 2024-10-11 21:42 UTC by manuel-rw

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-10-20 13:12 UTC, manuel-rw commented
Blocked by https://github.com/jlalmes/trpc-openapi/issues/441

2024-11-23 20:30 UTC, Meierschlumpf requested changes

2024-11-23 20:30 UTC, Meierschlumpf commented on packages/db/validationSchemas/app.ts
IMO one file for all schemas would make more sense as it's only 5 lines

2024-11-23 21:04 UTC, Meierschlumpf approved these changes

2024-11-23 21:05 UTC, merged