feat: plex integration
homarr-labs/homarr pull request #1342
Opened 2024-10-20 18:29 UTC by hillaliy

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-10-21 12:58 UTC, hillaliy commented
I need some help to fix lint error

2024-10-21 13:54 UTC, manuel-rw commented
You should move ``@types/xml2js`` to ``devDependencies`` because it's never needed in the production. It's only used when TypeScript builds / lints the app.

2024-10-21 16:33 UTC, hillaliy commented
sorry for many commits

2024-10-22 13:13 UTC, manuel-rw requested changes

2024-10-22 13:13 UTC, manuel-rw commented on packages/integrations/src/plex/plex-integration.ts
> +    if (!mediaContainer.Video) {
debug log here

2024-10-22 14:12 UTC, SeDemal requested changes
I haven't been able to try it much, but I found this: https://plexapi.dev/Intro
I'm not sure if it actually is native plex or for a plugin, but they seem to handle the responses as JSON, and they provide an sdk.
The xml2js option is good enough, I'm just saying it's worth looking into.

2024-10-22 14:12 UTC, SeDemal commented on packages/integrations/src/plex/plex-integration.ts
> +        if (typeof parsedResponse === "object" && parsedResponse !== null) {
You should check for specific data, any URL with an xml response would return valid.
Just checking for the existence of the "MediaContainer" element should be enough.

2024-10-22 14:12 UTC, SeDemal commented on packages/integrations/src/plex/plex-integration.ts
> +            type: PlexIntegration.getCurrentlyPlayingType(videoElement.$.type) ?? "video",
```TS
type: videoElement.$.live === "1" ? "tv" : this.getCurrentlyPlayingType(videoElement.$.type),
```

2024-10-22 14:14 UTC, SeDemal commented on packages/integrations/src/plex/plex-integration.ts
> +    const response = await fetch(`${this.integration.url}/status/sessions?X-Plex-Token=${token}`);
You fixed it already when I was doing my review, nvm good job

2024-10-22 14:14 UTC, SeDemal commented on packages/integrations/src/plex/plex-integration.ts
> +        return await fetch(`${this.integration.url}?X-Plex-Token=${token}`);
You fixed it already when I was doing my review, nvm good job

2024-10-22 18:07 UTC, manuel-rw submitted a review, later dismissed
Please wait for other reviewers to approve

2024-10-22 22:05 UTC, SeDemal requested changes

2024-10-22 22:05 UTC, SeDemal commented on packages/integrations/src/plex/plex-integration.ts
> +    const mediaContainer = data.MediaContainer;
Funny thing, oldmarr used element[0], meaning it didn't actually target a "MediaContainer".
In the case of music, the element is actually a "Track" and not a "MediaContainer".
Oldmarr was working by mistake. In your case though, you need to handle "data.Track" instead for music.

2024-10-23 14:18 UTC, merged