feat: add lidarr integration
homarr-labs/homarr pull request #1433
Opened 2024-11-05 21:50 UTC by manuel-rw

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-11-07 19:45 UTC, Meierschlumpf requested changes

2024-11-07 19:45 UTC, Meierschlumpf commented on apps/nextjs/public/images/apps/imvdb.png
Both images seem to be broken. When downloading them windows shows the following for me:
![image](https://github.com/user-attachments/assets/6c05b004-f52d-48ff-aa3c-5ac182798f6d)

2024-11-07 19:45 UTC, Meierschlumpf commented on packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
> +        logo: "/images/apps/imdb.png",
Probably wrong image

2024-11-08 21:41 UTC, Meierschlumpf requested changes

2024-11-16 18:34 UTC, SeDemal commented on packages/integrations/src/media-organizer/lidarr/lidarr-integration.ts
> +    const links: CalendarEvent["links"] = [];
Use a map on event.artist.links and switch statement instead? This avoids all the non-null assertions.

2024-11-16 18:36 UTC, SeDemal commented
Also, could we switch to svg for the images since you are changing them anyway?

2024-11-19 22:06 UTC, Meierschlumpf approved these changes

2024-11-20 18:03 UTC, merged