feat: language selector
homarr-labs/homarr pull request #484
Opened 2024-05-12 15:39 UTC by manuel-rw

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-05-12 20:44 UTC, Meierschlumpf commented on apps/nextjs/src/components/language/language-combobox.tsx
> +  const languageKeys = Object.keys(mapping) as SupportedLanguage[];
Why not just using supportedLanguages? It's exported directly

2024-05-15 20:45 UTC, Meierschlumpf requested changes

2024-05-15 20:45 UTC, Meierschlumpf commented on apps/nextjs/src/components/user-avatar-menu.tsx
> +              href={`/manage/users/${session.data?.user.id}`}
This link is wrong

2024-05-17 22:19 UTC, Meierschlumpf submitted a review, later dismissed

2024-05-18 11:54 UTC, Meierschlumpf approved these changes

2024-05-18 11:54 UTC, merged

2024-05-18 12:14 UTC, ajnart commented
noice