feat: add i18n translated form errors
homarr-labs/homarr pull request #509
Opened 2024-05-17 10:05 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-05-17 17:41 UTC, manuel-rw requested changes

2024-05-17 17:41 UTC, manuel-rw commented on packages/form/src/index.ts
elegant solution!

2024-05-17 17:41 UTC, manuel-rw commented on packages/form/src/messages.ts
> +    if ("startsWith" in issue.validation) {
Explain with a comment what this does / why you make this check

2024-05-18 13:34 UTC, Meierschlumpf commented on packages/form/src/index.ts
Thanks 😄

2024-05-18 14:54 UTC, manuel-rw approved these changes

2024-05-18 14:55 UTC, merged