feat: update prettier configuration for print width
homarr-labs/homarr pull request #519
Opened 2024-05-18 16:26 UTC by ajnart

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-05-18 20:20 UTC, manuel-rw submitted a review, later dismissed
please format (you can do this by running ``pnpm format:fix``)

2024-05-18 20:32 UTC, ajnart commented
Alright 😀

2024-05-19 15:01 UTC, Meierschlumpf requested changes

2024-05-19 15:01 UTC, Meierschlumpf commented on apps/websocket/wssServer.cjs
This one as well should be removed

2024-05-19 15:02 UTC, ajnart commented on apps/tasks/tasks.cjs
Good catch

2024-05-19 20:36 UTC, Meierschlumpf approved these changes

2024-05-19 20:37 UTC, ajnart commented
Thanks for the fix

2024-05-19 20:38 UTC, merged