feat: add simple app ping
homarr-labs/homarr pull request #580
Opened 2024-05-30 04:37 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-05-31 15:32 UTC, manuel-rw requested changes
Do I understand this correctly?

- The ping will only fail when there is an error within the fetch
- The status code is only used for the display in the frontend
- The ping will only be performed when it was registered over redis?

Can you attach also some screenshots?
Have you done some testing with invalid certificates, redirects, ...?

2024-05-31 15:32 UTC, manuel-rw commented on apps/tasks/src/lib/queue/worker.ts
> +      logger.error(err);
Add more info (eg. that this error occurred in a worker)

2024-05-31 15:32 UTC, manuel-rw commented on apps/tasks/src/lib/cron-job/creator.ts
> +          logger.error(error);
Add more info (see other comment)

2024-05-31 15:32 UTC, manuel-rw commented on packages/ping/src/index.ts
> +    logger.error(error);
Log where this error happened.

2024-05-31 15:32 UTC, manuel-rw commented on packages/ping/src/index.ts
> +    return { error: "Unknown error" };
Maybe it would be useful to put this in an exported function since it could be used elsewhere too?

2024-05-31 15:32 UTC, manuel-rw commented on packages/widgets/src/app/component.tsx
> +  const shouldPingRun = Boolean(app?.href) && options.pingEnabled;
Rename to shouldRunPing?

2024-06-02 09:38 UTC, Meierschlumpf commented
> Do I understand this correctly?
> 
> * The ping will only fail when there is an error within the fetch
> * The status code is only used for the display in the frontend
> * The ping will only be performed when it was registered over redis?
> 
> Can you attach also some screenshots? Have you done some testing with invalid certificates, redirects, ...? Do you want to push tests later?

The ping itself will only fail when there is an error with the fetch:
> Yes it will only show an error then. On the frontend it will check also if the statuscode was greater than 500 which would be a server error

The status code is only used for the display in the frontend:
> Yes and to check if it's greater than 500 to show a red dot if needed

The ping will only be performed when it was registered over redis:
> Yes it will only ping an url that was added to the redis list. If the websocket disconnects it will remove the url again.

I was not able to test it with invalid certificates and such. I'll try with a redirect within the next app now
I'll take a look on what tests make sense here within this pull request and add them accordingly

2024-06-02 09:49 UTC, Meierschlumpf commented
Okay redirect works

2024-06-02 11:08 UTC, manuel-rw approved these changes

2024-06-06 10:00 UTC, manuel-rw approved these changes

2024-06-08 15:33 UTC, merged