feat: Add `million-lint`
homarr-labs/homarr pull request #607
Opened 2024-06-02 08:30 UTC by ajnart

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-06-02 11:05 UTC, manuel-rw requested changes

2024-06-02 11:05 UTC, manuel-rw commented on .gitignore
> +apps/nextjs/.million/store.json
Shouldn't we ignore the entire ``.million`` directory?

2024-06-02 11:05 UTC, manuel-rw commented on .vscode/extensions.json
> +    "lokalise.i18n-ally",
Out of scope

2024-08-25 16:07 UTC, manuel-rw submitted a review, later dismissed

2024-08-29 20:24 UTC, SeDemal approved these changes

2024-08-29 20:25 UTC, merged