feat: add tasks page
homarr-labs/homarr pull request #692
Opened 2024-06-19 18:25 UTC by manuel-rw

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-06-19 18:26 UTC, manuel-rw commented
@Meierschlumpf can you suggest an implementation for listing the tasks and triggering them? I was thinking about publishing redis and pushing real time updates before and after a task started / completed

2024-06-22 20:22 UTC, Meierschlumpf commented
Has been added in branch `cron-job-status-runner`, will be rebased into this branch soon

2024-06-27 18:08 UTC, Meierschlumpf requested changes

2024-06-29 09:19 UTC, Meierschlumpf approved these changes
Looks good, your pnpm lock is not up to date

2024-06-29 11:38 UTC, manuel-rw commented
dismissed review due to rebase

2024-06-30 14:03 UTC, Meierschlumpf requested changes

2024-06-30 14:03 UTC, Meierschlumpf commented on apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx
> +                {job.status?.lastExecutionStatus === "error" && <Badge color="red">Error</Badge>}
Translations missing

2024-07-01 04:35 UTC, Meierschlumpf requested changes
Would be happy if you don't force push as it is a lot easier to review only those changes made and not again taking a look on the whole file content.

2024-07-01 04:35 UTC, Meierschlumpf commented on packages/translation/src/lang/en.ts
> +  },
It seems like this stuff is back again :joy:

2024-07-01 04:35 UTC, Meierschlumpf commented on apps/nextjs/src/app/[locale]/manage/tools/tasks/_components/jobs-list.tsx
> +import { TranslationKeys } from "@homarr/translation";
When you are already addressing something, you can also add type to this import

2024-07-01 04:41 UTC, Meierschlumpf approved these changes

2024-07-01 16:57 UTC, manuel-rw commented
> Would be happy if you don't force push as it is a lot easier to review only those changes made and not again taking a look on the whole file content.

Sorry, will do in the future 😅👍

2024-07-01 16:57 UTC, merged