feat: add dynamic section
homarr-labs/homarr pull request #842
Opened 2024-07-21 11:13 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

Current issues I'm facing:

- minRow would be a nice addition so that it would always have the full grid available to put items inside and not just the first row (or if items are there the rows where items are). I tried it with setting the minRow property in options again when the height of the section changed. But until now without success

2024-07-25 18:20 UTC, Meierschlumpf commented on apps/nextjs/src/components/board/sections/content.tsx
> +          innerRef={refs.items.current[item.id] as React.RefObject<HTMLDivElement>}
May be undefined

2024-07-25 18:20 UTC, Meierschlumpf commented on apps/nextjs/src/components/board/sections/content.tsx
> +          minWidth={item.type === 'section' ? Math.max(...item.items.map(item => item.xOffset + item.width), ...board.sections.filter((section): section is DynamicSection => section.kind === 'dynamic
Improve

2024-07-25 18:20 UTC, Meierschlumpf commented on apps/nextjs/src/components/board/sections/section-actions.tsx
> +      console.log("moveInnerSectionToSection", innerSectionId, sectionId, positionProps);
Remove `console.log`

2024-08-01 11:03 UTC, Meierschlumpf commented
Calculation of size solved:

![image](https://github.com/user-attachments/assets/1972256a-9253-4475-9f90-120611efa9f6)

2024-08-08 17:11 UTC, manuel-rw requested changes
Looks good. Would be nice if you add more comments - the Gridstack API is very complex and I think it would be useful if the "bar for entry" would be lower - even I can't follow all the time.

Also, would you be available to quickly test & try this out together in a call before we merge this? Thank you for your work 🚀❤️

2024-08-08 17:11 UTC, manuel-rw commented on apps/nextjs/src/components/board/sections/gridstack/init-gridstack.ts
> +      margin: 10, // Math.round(Math.max(Math.min(refs.wrapper.current.offsetWidth / 100, 10), 1)),
Remove commented out code

2024-08-08 17:11 UTC, manuel-rw commented on apps/nextjs/src/components/board/sections/gridstack/use-gridstack.ts
> +        });
Explain with a comment why you suppress the error

2024-08-10 09:29 UTC, manuel-rw approved these changes

2024-08-10 09:54 UTC, Meierschlumpf commented
> Also, would you be available to quickly test & try this out together in a call before we merge this? Thank you for your work 🚀❤️

sure

2024-08-10 10:36 UTC, manuel-rw approved these changes

2024-08-10 10:37 UTC, merged