feature: usenet downloads
homarr-labs/homarr pull request #844
Opened 2024-07-21 13:37 UTC by manuel-rw

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [ ] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [ ] Pull request targets ``dev`` branch
- [ ] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

2024-07-23 16:00 UTC, hillaliy commented on packages/widgets/src/usenet-downloads/component.tsx
> +export default function VideoWidget({integrationIds, serverData}: WidgetComponentProps<"usenet-downloads">) {
Change VideoWidget to UsenetDownloadsWidget

2024-09-07 15:47 UTC, Meierschlumpf commented
The build error is happening because of a upstream dependency issue with crypto-hash, that we provided a suggestion to fix it in the used dependency for qBittorrent: https://github.com/scttcper/torrent-file/pull/77

2024-09-10 19:51 UTC, SeDemal approved these changes

2024-09-11 13:37 UTC, Meierschlumpf requested changes

2024-09-11 13:37 UTC, Meierschlumpf commented on packages/api/src/router/widgets/media-requests.ts
> +      createManyIntegrationOfOneItemMiddleware("query", ...getIntegrationKindsByCategory("mediaRequest")),
What about putting this into a seperate function as well?

2024-09-11 13:37 UTC, Meierschlumpf commented on packages/api/src/router/widgets/media-server.ts
> +    .unstable_concat(createManyIntegrationMiddleware("query", ...getIntegrationKindsByCategory("mediaService")))
What about putting this into a seperate function as well?

2024-09-11 13:37 UTC, Meierschlumpf commented on packages/api/src/router/widgets/smart-home.ts
> +    .unstable_concat(createOneIntegrationMiddleware("interact", ...getIntegrationKindsByCategory("smartHomeServer")))
What about putting this into a seperate function as well?

2024-09-11 13:37 UTC, Meierschlumpf commented on packages/integrations/test/nzbget.spec.ts
> +  // */
Please remove this code, it will still be in the history if needed at some point

2024-09-11 14:32 UTC, Meierschlumpf approved these changes

2024-09-11 14:37 UTC, SeDemal approved these changes

2024-09-11 15:30 UTC, merged