feat: reset password cli
homarr-labs/homarr pull request #903
Opened 2024-08-02 08:43 UTC by Meierschlumpf

<br/>
<div align="center">
  <img src="https://homarr.dev/img/logo.png" height="80" alt="" />
  <h3>Homarr</h3>
</div>

**Thank you for your contribution. Please ensure that your pull request meets the following pull request:**

- [x] Builds without warnings or errors (``pnpm buid``, autofix with ``pnpm format:fix``)
- [x] Pull request targets ``dev`` branch
- [x] Commits follow the [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] No shorthand variable names are used (eg. ``x``, ``y``, ``i`` or any abbrevation)

![image](https://github.com/user-attachments/assets/5006bff1-1488-4640-b44b-5f0779d78b1a)

2024-08-02 08:59 UTC, manuel-rw requested changes

2024-08-02 08:59 UTC, manuel-rw commented on packages/cli/src/index.ts
> +const resetPassword = command({
Extract to it's own file

2024-08-02 08:59 UTC, manuel-rw commented on packages/cli/src/index.ts
> +    const newPassword = crypto.randomUUID();
Is UUID a good idea for a password? I'd prefer a secure random generator from the crypto module instead

2024-08-04 08:53 UTC, manuel-rw approved these changes

2024-08-04 19:44 UTC, SeDemal approved these changes

2024-08-04 19:44 UTC, merged